services:
  frontend: 
    image: marimo28/quirknotes_frontend:latest
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
      image: marimo28/quirknotes_backend:latest
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
